"""create statements table

Revision ID: 06517aa4bdb8
Revises: 
Create Date: 2026-06-14 22:34:49.796510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06517aa4bdb8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank', sa.String(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('starting_balance', sa.Float(), nullable=False),
    sa.Column('closing_balance', sa.Float(), nullable=False),
    sa.Column('transactions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statements_id'), 'statements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statements_id'), table_name='statements')
    op.drop_table('statements')
    # ### end Alembic commands ###
