"""added a investment entry

Revision ID: 9a5016b636e6
Revises: f549f4112971
Create Date: 2026-06-16 22:40:34.647737

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9a5016b636e6"
down_revision: Union[str, Sequence[str], None] = "f549f4112971"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "monthly_stats",
        sa.Column(
            "total_invested", sa.Float(), server_default="0.0", nullable=False
        ),  # 👈 Added server_default here
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("monthly_stats", "total_invested")
    # ### end Alembic commands ###
