"""create monthly stats table

Revision ID: f549f4112971
Revises: 06517aa4bdb8
Create Date: 2026-06-16 21:57:42.277617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f549f4112971'
down_revision: Union[str, Sequence[str], None] = '06517aa4bdb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=3), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('gross_income', sa.Float(), nullable=False),
    sa.Column('lifestyle_expenses', sa.Float(), nullable=False),
    sa.Column('net_savings', sa.Float(), nullable=False),
    sa.Column('savings_rate_pct', sa.Float(), nullable=False),
    sa.Column('fixed_vs_variable_ratio', sa.String(length=50), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_stats_id'), 'monthly_stats', ['id'], unique=False)
    op.create_index(op.f('ix_monthly_stats_month'), 'monthly_stats', ['month'], unique=False)
    op.create_index(op.f('ix_monthly_stats_year'), 'monthly_stats', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_stats_year'), table_name='monthly_stats')
    op.drop_index(op.f('ix_monthly_stats_month'), table_name='monthly_stats')
    op.drop_index(op.f('ix_monthly_stats_id'), table_name='monthly_stats')
    op.drop_table('monthly_stats')
    # ### end Alembic commands ###
