"""transaction link

Revision ID: fc73abd5f740
Revises: d326343e5c30
Create Date: 2026-06-18 21:58:43.411666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc73abd5f740'
down_revision: Union[str, Sequence[str], None] = 'd326343e5c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('bank_statement_linked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'bank_statement_linked')
    # ### end Alembic commands ###
